allenai/ai2thor

- ai2thor/_quality_settings.py
- unity/ProjectSettings/QualitySettings.asset
Makes WebGL quality setting number 7
> Quality settings change

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
Fixing the hideseek object randomizer. Also centralized the logging of error messages.
> Fixing the hideseek object randomizer.

- tasks.py
Makes all unityweb files content addressable
> Changes webgl deploy cache settings

- unity/Assets/Physics/Physics Scenes/FloorPlan10_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan14_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan17_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan18_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan19_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan1_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan20_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan22_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan24_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan26_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan28_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan2_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan30_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan3_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan5_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan9_physics.unity
edited mesh collision on sink faucets, also corrected any erroneous tags and layer assignments
> sink faucet collision edits

- unity/Assets/Physics/Physics Scenes/FloorPlan15_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan21_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan226_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan23_physics.unity
- unity/Assets/Physics/Physics Scenes/FloorPlan28_physics.unity
some living rooms and kitchens also had blinds that needed updating
> Added Blinds to Some Living Rooms and Kitchens

- tasks.py
Re-enables demo autodeploy after tests
> Demo autodeploy 

- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Also updated the `OpenObjectAtLocation` method.
> Fixing some warnings about unused variables and an error when determining if a target position was within scene bounds.

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
Actually needed to destroy the agents otherwise the error would occur every so often regardless of the agent visibility.
> Part 2 of fixing a bug where resetting a scene with multiple visible agents present would cause the player to crash.

- unity/Assets/Physics/SimObjsPhysics/Living Room Objects/Television/Prefabs/Television_1.prefab
- unity/Assets/Scenes.meta
- unity/Assets/Scenes/SourceFiles_physics.meta
- unity/Assets/Scenes/SourceFiles_physics/Materials.meta
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Also added some small change that previously should have been committed w.r.t. the television prefab.
> Getting agent color changing to work.

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObj.cs
- unity/Assets/Scripts/SimObjPhysics.cs
In particular, removed the `isVisible` and `isInteractable` flags.
>  Performance improvements and removing some unused flags in SimObjPhysics.

- unity/Assets/Scripts/DebugDiscreteAgentController.cs
Added missing refactored script
> Added controller

- unity/Assets/Scripts/ObjectHighlightController.cs
Simplifies shader swap logic and fixes transparent objects from disappearing when highlighted.
> Alpha object fix

- unity/Assets/Physics/Test_Scene_randomSpawn.unity
- unity/Assets/Prefabs/Systems/DeferredDecalSpawnPlane.prefab
- unity/Assets/Prefabs/Systems/QuadDecalSpawnPlane.prefab
> Decals Fix

- unity/ProjectSettings/GraphicsSettings.asset
- unity/ProjectSettings/QualitySettings.asset
Brings back High WebGL quality setting
> Demo quality settings

- unity/Assets/Scripts/DebugFPSAgentController.cs
> Mouse enable disable functions to fps controller

- unity/Assets/Physics/SimObjsPhysics/Miscellaneous Objects/Vase/Prefabs/Vase_Medium_5.prefab
- unity/Assets/Scenes/FloorPlan1_physics.unity
- unity/Assets/Scenes/FloorPlan202_physics.unity
- unity/Assets/Scripts/FirstPersonCharacterCull.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
- unity/Assets/Scripts/SyncTransform.cs
-adjusted missing property on Vase prefab
-fixed null reference in SceneManager in FloorPlan1 and FloorPlan202
-fixed agent not appearing when using ToggleMapView action
> some bug fixes to 2.0

- unity/Assets/QuickMaterials/Liquids/TestTransparent.mat
- unity/Assets/QuickMaterials/Liquids/TestTransparent.mat.meta
- unity/Assets/QuickMaterials/Liquids/TestTransparent.shader
- unity/Assets/QuickMaterials/Liquids/TestTransparent.shader.meta
- unity/Assets/SpecialFX/Liquid.shader
- unity/Assets/SpecialFX/Liquid_Volume_Test_Scene.unity
Testing transparency windows vs mac
> Shader test

- unity/Assets/Scripts/PhysicsSceneManager.cs
Example
```python
env = ai2thor.controller.Controller()
env.start()
object_poses = [{"objectName": "Alarm_Clock_19", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.8197357, "x": 2.45610785, "z": 0.054755792}}, {"objectName": "Box_19", "rotation": {"y": 29.0781651, "x": 0.0, "z": 0.0}, "position": {"y": 0.2277, "x": 0.2524, "z": -2.042}}, {"objectName": "Book_19", "rotation": {"y": 0.0, "x": 0.0, "z": 0.0}, "position": {"y": 0.7308113, "x": 0.3694262, "z": 1.497829}}, {"objectName": "Waving_Statue_2", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.825887859, "x": 2.45610952, "z": 0.623093963}}, {"objectName": "Cellphone_1", "rotation": {"y": 270.000153, "x": 0.0, "z": 0.0}, "position": {"y": 0.9018043, "x": 2.45610833, "z": 0.244201869}}, …
```
> Enables restoring a state to a previous metadata dump

- ai2thor/controller.py
- ai2thor/interact.py
- ai2thor/robot_controller.py
- ai2thor/server.py
- tasks.py
* Upgrades interact invoke task to save images of real agent at every step
* Flips RB values for agent's color image
* Option to flip image vertically and horizontally
* Flips depth image horizontally, as it was incorrect
> Interact controller upgrade, image fixes

- unity/Assets/ImageSynthesis/Shaders/Depth.shader
- unity/Assets/ImageSynthesis/Shaders/DepthBW.shader
- unity/ProjectSettings/GraphicsSettings.asset
Shader fix for Metal requirement in Mac
> Depth Image mac fix

- ai2thor/interact.py
- ai2thor/util/scene_yaml_edit.py
- tasks.py
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Setup and utility functions for getting Shortest Path to objects using navmeshes.
> Shortest Path Setup

- ai2thor/controller.py
- ai2thor/interact.py
- ai2thor/robot_controller.py
- ai2thor/server.py
- tasks.py
- unity/Assets/Editor/Build.cs
- unity/Assets/ImageSynthesis/ImageSynthesis.cs
- unity/Assets/ImageSynthesis/Shaders/Depth.shader
- unity/Assets/ImageSynthesis/Shaders/DepthBW.shader
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/ProjectSettings/GraphicsSettings.asset
- unity/ProjectSettings/ProjectSettings.asset
* Unifies depth with real
* Supports different units
* Shader rewrites without hacks and magic numbers
> Depth fixes

- unity/Assets/Scripts/BaseFPSAgentController.cs
Removes agent initialization for `tall` in Unity initiated start function
> Fixes initialization for 'bot' mode

- ai2thor/util/metrics.py
- tasks.py
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Simplifies way to compute shortest paths and spl
> SPL cleanup

- .gitignore
- ai2thor/util/scene_yaml_edit.py
- tasks.py
- unity/Assets/Prefabs/Systems/DebugPoint.prefab
- unity/Assets/Prefabs/Systems/DebugPoint.prefab.meta
- unity/Assets/Prefabs/Systems/GridRenderer.prefab
- unity/Assets/Prefabs/Systems/GridRenderer.prefab.meta
- unity/Assets/Prefabs/Systems/TargetPoint.prefab
- unity/Assets/Prefabs/Systems/TargetPoint.prefab.meta
- unity/Assets/QuickMaterials/Misc/DebugPoint.mat
- unity/Assets/QuickMaterials/Misc/DebugPoint.mat.meta
- unity/Assets/QuickMaterials/Misc/LineRendererPoint.mat
- unity/Assets/QuickMaterials/Misc/LineRendererPoint.mat.meta
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/NavMeshSetup.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
* Adds missing visualization prefabs
* Makes line and font rendering smoother
* Git ignore fixes
> Visualization prefabs and fixes

- ai2thor/util/scene_yaml_edit.py
- tasks.py
- unity/Assets/Scripts/NavMeshSetup.cs
Updates scripts for building scenes in different paths
> Navmesh Scripts

- ai2thor/video_controller.py
- setup.py
- unity/Assets/Scripts/AgentManager.cs
Allows for basic animations with the video controller and changes to the color of the skybox from python.
> Video controller merge

- MANIFEST.in
It would be helpful to include the license file in the source distribution
> Create MANIFEST.in to package license with source distribution

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
add a `objectIds []` in AgentManager.cs at action field and a new action `RemoveObjsFromScene` in BaseFPSAgentController.cs
> add RemoveObjsFromScene

- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Manual Physics step simulation
> Move Arm functions without Rendering

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
* Adds optional restriction to moveArm function to not move behind shoulder.
* Refactors no render code and unifies into only 2 movement functions, IEnumerator and manual physics step
> Exp room refactor

- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Flags for rotate were not being passed accordingly
> Exp room flag fix

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/ContinuousMovement.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
-switching to event based collision checks
-updating metadata of joint rotations to account for "angler" game objects in arm joints
> Exp room new arm

- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
> Revert "Fix pushAngle in DirectionalPush"

- unity/Assets/Scripts/PhysicsSceneManager.cs
No functionality should change. Just cleans up various indentations and bracket styles on this single file.
> PhysicsSceneManager Spacing

- ai2thor/server.py
- ai2thor/tests/test_fifo_server.py
- ai2thor/tests/test_server.py
Fixes https://github.com/allenai/ai2thor/issues/586, and adds a regression test that fails before the change and passes after the change.
> Extend `NumpyAwareEncoder` to understand arrays

- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
This latest IK Robot Arm Controller script update should fix all NaN issues. Please re-run the relevant slide tests to confirm this is the case.
> Fixed IK NaN issue

- ai2thor/tests/test_unity.py
This eliminates the issue of ensuring that tests run in a particular order since we reset the controller prior to it being used for a test.
> refactor unity tests to reset prior to usage of controller

- tasks.py
* Removes deprecated start call
* Allows to benchmark builds based on commit-id
> Benchmark task update

- ai2thor/build.py
- ai2thor/controller.py
- ai2thor/downloader.py
- ai2thor/interact.py
- ai2thor/mock_real_server.py
- ai2thor/offline_controller.py
- ai2thor/robot_controller.py
- ai2thor/server.py
- ai2thor/util/lock.py
- ai2thor/util/metrics.py
- ai2thor/util/scene_yaml_edit.py
- ai2thor/video_controller.py
- ai2thor/wsgi_server.py
- arm_test/arm_counter_30fps_fixed_update.py
- arm_test/arm_counter_30fps_fixed_update_random_sleep.py
- arm_test/arm_counter_30fps_simulate.py
- arm_test/arm_counter_30fps_simulate_pause_return_start.py
- arm_test/arm_stuck_test_wait_frame.py
- arm_test/base.py
- arm_test/check_determinism_different_machines.py
- arm_test/check_determinism_event_collision_different_machines.py
- tasks.py
This PR addresses the majority of the issues identified by lgtm.com https://lgtm.com/projects/g/allenai/ai2thor?mode=list.  Hopefully this brings our Code quality grade up from a D.
> Resolve errors, warnings, recommendations from lgtm.com

- ai2thor/video_controller.py
This PR addresses  [warnings](https://lgtm.com/projects/g/allenai/ai2thor/snapshot/272f5b029e0ef2b86939b71a1b55ad0e32cceef8/files/ai2thor/video_controller.py?sort=name&dir=ASC&mode=list#x59e138d0abb235d:2) found by lgtm.com regarding unreachable code.
> remove unreachable code in video_controller._rotate

- unity/Assets/Scripts/ImageSynthesis/ImageSynthesis.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
Running dotnet-format to pick a few unformatted statements
> Run dotnet-format

- unity/Assets/Scenes/FloorPlan429_physics.unity
fixing sink mesh collider on wrong collision layer, causing "GetReachablePositions" to return false valid positions near the sink.
note: delaying merge of this PR to `main` until May 26th due to Neurips code freeze.
> Update Sink Geometry FloorPlan429_physics.unity

- unity/Assets/Scripts/ObjectHighlightController.cs
Currently, throwing an object is uncontrollably fast. I'm not sure if 400f is low enough, since I can't test it until it is live. But, it seems like a reasonable starting point to try.
> [Demo] Slow down throw speed

- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/ProceduralData.cs
- unity/Assets/Scripts/ProceduralTools.cs
-renames to `SpawnObjectInReceptacle` and `SpawnObjectInReceptacleRandomly`
-adding new generic `SpawnObject` action taking a `HouseObject`
-adding `objectId` and `rotation` params to all spawn actions
> Nanna Updates

- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
> update camera culling mask

- unity/Assets/Scripts/BaseFPSAgentController.cs
Addresses https://github.com/allenai/ai2thor/commit/fd272ce08dcb86ed806649c4ce268f83d1f59a09#r54320561.
> Sets `cameraOrthSize` on `ToggleMapView`

- unity/Assets/Scripts/AgentManager.cs
quick edit to enable autosim by default, similar to how it is done in WebGL builds.
> Enable physics autosim at start

- unity/Assets/Scripts/Dirty.cs
Tiny refactor to improve efficiency of OnTriggerStay of the Dirty component.
> moving isDirtyCheck into outer if condition in Dirty

- unity/Assets/Scripts/DebugInputField.cs
A cast error was thrown when using a non-physics controller in the DebugInputField.
> OnGui in DebugInputField when using a non-physicscontroller

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/ArmAgentController.cs
- unity/Assets/Scripts/BaseAgentComponent.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/ConnectionProperties.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/DroneFPSAgentController.cs
- unity/Assets/Scripts/ExpRoom/PhysicsRemoteFPSAgentController_partial_ExpRoom.cs
- unity/Assets/Scripts/FirstPersonCharacterCull.cs
- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Scripts/LocobotFPSAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
- unity/Assets/Scripts/PrefabNameRevert.cs
- unity/Assets/Scripts/ProceduralData.cs
- unity/Assets/Scripts/ProceduralRoomEditor.cs
- unity/Assets/Scripts/ProceduralTools.cs
- unity/Assets/Scripts/RoomProperties.cs
- unity/Assets/Scripts/SimObjPhysics.cs
- unity/Assets/Scripts/SimObjType.cs
- unity/Assets/Scripts/UtilityFunctions.cs
- unity/Assets/Scripts/WallProperties.cs
Formatting nanna with  `invoke format-cs`
> reformatting via invoke format-cs

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/JavaScriptInterface.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
* Fixes to be able to call same Initialize as in pyhton
* Uses AgentManager's ProcessControlCommand instead of agent
* Debug build logging
> WebGL multiple agent type support

- unity/Assets/Scripts/AgentManager.cs
- unity/Packages/manifest.json
- unity/Packages/packages-lock.json
Updates cloudrendering with newtonsoft library dependency, and fixes property access of json object.
> Fixes webgl build

- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/ImageSynthesis/ImageSynthesis.cs
- unity/Assets/Scripts/RobotArmTest/GripperCamera.prefab
- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
Fixes editor rendering when gripper and secondary cameras overwriting depth buffer.
> Rendering issue when gripper camera

- unity/Assets/Scripts/CanOpen_Object.cs
- unity/Assets/Scripts/CanToggleOnOff.cs
Follow-up fixes to open-close logic
> Nanna openclose copy

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/NavMeshSetup.cs
- unity/Assets/Scripts/ProceduralTools.cs
Tags agent to be ignored as part of navmesh in build action and procedural house creation
> Ignores agent when navmesh rebuild

- unity/Assets/Scenes/FloorPlan_test-dev2_2.meta
- unity/Assets/Scenes/FloorPlan_test-dev2_2.unity.meta
- unity/Assets/Scenes/FloorPlan_test-dev2_2/NavMesh.asset.meta
- unity/Assets/Scripts/ArticulatedAgentController.cs
- unity/Assets/Scripts/ArticulatedAgentSolver.cs
- unity/Assets/Scripts/ArticulatedArmController.cs
- unity/Assets/Scripts/ArticulatedArmJointSolver.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
(1) Bug fixes to limits code, (2) adding new interactive debug commands, (3) respecting the maxForce parameter when moving the arm and body, (4) resetting drive targets after moving.
> AB Agent Improvements.

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/ArticulatedAgentSolver.cs
- unity/Assets/Scripts/DebugInputField.cs
- Checks for finger dislodgement by using local transform of original state
- New `Error` AgentState for Emit state machine
- Remaining bug, reset does not seem to work properly for AB agent after having done some AB actions
> Dislodgement check

- tasks.py
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/ProceduralTools.cs
- unity/Assets/Scripts/RuntimePrefab.cs
Adding code to let us more easily render an object from multiple angles at runtime.
> Rendering an object for given angles
