allenai/ai2thor

- unity/Assets/Scripts/DiscreteRemoteFPSAgentController.cs
Without this change, every time a new scene is loaded, the grid has to be reset because the Discrete object is created anew. Making it a static variable applies the change to any future scenes also loaded, but it can be changed later by calling initialize again.
This also adds in a check that the grid size is greater than some small value in case the user doesn't ever specify the grid size.
> Changes gridSize to be a static variable

- unity/Assets/Prefabs/SimObjs/UNFINISHED/Appliances/Fridges/Fridge1.prefab
- unity/Assets/Prefabs/SimObjs/UNFINISHED/Appliances/Fridges/Fridge2.prefab
- unity/Assets/Prefabs/SimObjs/UNFINISHED/Appliances/Fridges/Fridge3.prefab
The old height was not enough to fully encapsulate the agent, so the visibility check always failed.
> made fridge box taller

- ai2thor/controller.py
I took a look at this issue:
https://github.com/allenai/ai2thor/issues/29
I also needed a similar feature so I added the grid_size as a parameter. Currently for a project, I'm trying to write a layer to make this compatible in continuous space. The grid_size and the grid_points allow me to create some kind of a map of the environment which I'm planning on using for collision detection. I got down to grid_size of 0.05 but I'm running into some issues if I go lower than that.
Thank you for the great simulator!
> accept grid_size as parameter for BFSController

- ai2thor/_quality_settings.py
- ai2thor/controller.py
- unity/ProjectSettings/QualitySettings.asset
Adding a dummy quality setting to avoid unity bug where quality level 0 is ignored on startup.
> Adding a dummy quality setting to avoid unity bug where quality level 0 is ignored on startup.

- unity/Assets/Scenes/FloorPlan14_physics.unity
- unity/Assets/Scenes/FloorPlan18_physics.unity
- unity/Assets/Scenes/FloorPlan28_physics.unity
- unity/Assets/Scenes/FloorPlan29_physics.unity
- unity/Assets/Scenes/FloorPlan30_physics.unity
- unity/Assets/Scenes/FloorPlan6_physics.unity
-some cabinets in kitchens did not have their "ignore objects" referenced correctly to ignore their neighbors when open/closing, preventing them from opening at all.
> fixed open/close collision on cabinets in Kitchens

- README.md
- **Remove start call**: With the start method depreciated and `local_executable_path` as a parameter for the `Controller` constructor, the previously documented code is not optimal since it would be calling `start` twice. (However, it would still work!)
- **Remove local-build**: After running `invoke local-build`, the previous path was **incorrect** and needed to remove **local-build**. The method that defines the path is in **tasks.py** defined [**here**](https://github.com/allenai/ai2thor/blob/master/tasks.py#L47), and does NOT contain `/local-build/`.
> Fix Unity Development build method documentation

- ai2thor/controller.py
- tasks.py
Integrating GitHub actions with Python basically checks to make sure that everything compiles using flake8. An error is caused when using BlockingIOError, since that was not introduced until Python3. However, the io module contains the BlockingIOError exception for both Python2 and Python3.
I ran tests locally to ensure everything works.
View log of original errors caused:
[Windows CI](https://github.com/mattdeitke/ai2thor/commit/829f9f77e903535cda859401253c12af6fac866b/checks?check_suite_id=398810603)
[Ubuntu CI](https://github.com/mattdeitke/ai2thor/commit/829f9f77e903535cda859401253c12af6fac866b/checks?check_suite_id=398810594)
[Mac CI](https://github.com/mattdeitke/ai2thor/commit/829f9f77e903535cda859401253c12af6fac866b/checks?check_suite_id=398810625)
View solution log, which simply …
> Python2 blocking io error and printing error -> warning

- ai2thor/controller.py
- ai2thor/tests/test_unity.py
It's been tested and works well for a variety of initializations. Tests can simply be run with
```python
from ai2thor.controller import Controller
c = Controller(width=64, height=64)
c.last_event.frame.shape
```
Also raised in #87.
> Front-end support for height x width < 300x300

- unity/Assets/Physics/Test_Scene_W.unity
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/Contains.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/ObjectSpecificReceptacle.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
- unity/Assets/Scripts/SimObjPhysics.cs
There are two main changes with this pull:
1) Receptacle Behavior - receptacles used to update their contents with each fixed update using a series of OnTrigger calls. This has now been replaced with Physics Overlap Boxes that snapshot the contents of the receptacle whenever an actionFinished() call is made. This should improve physics performance somewhat (hopefully a lot) due to minimizing the number of fixed update checks are happening across all receptacle objects.
2) New (undocumented for now?) Initialization parameter to allow more control over how long actions yield to return when waiting for an object to come to rest- Previously all actions that could move an object in a way that it should wait for the object to come to rest before returning actionFinished() defaulted to 2 second …
> Receptacle snapshot

- unity/ProjectSettings/AudioManager.asset
I noticed when running a large number of experiments that the pulseaudio process on Linux would use up to 100% of a CPU.  This PR disables the Audio in thor. When I ran a build with the audio disabled pulseaudio uses no CPU.
> disabling unity audio

- unity/Assets/Scripts/BaseFPSAgentController.cs
adding a seenPoints hashset to keep track of which points have been visited during the BFS for shortestPath and reachablePositions
I feel pretty confident about this, but want to be sure that this doesn't introduce any errors.  The output for both reachablePositions and shortestPath were identical when I tested this with and without the seenPoints hashset.  The benefit I saw is that the number of steps taken went from around 400-> 100 for reachable positions (FloorPlan28) and 190 -> 66 for shortestPath (FloorPlan28 mug).
> seenPoints for reachablePositions and shortestPath

- unity/Assets/Scripts/BaseFPSAgentController.cs
Using visibilityScheme of Distance combined with this change and fastAction emit leads to ~10x speed improvement for GetShortestPath.  Before this at each point we check the visibility of all objects at each point, when only one object is needed.
> using isSimObjVisible with shortestPath calculation if visibilityScheme is distance

- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
Simple workaround to add back agent's capsule into collision test, necessary for continuous move.
> Adding agent capsule to be included in Arm Collision

- ai2thor/controller.py
- ai2thor/util/metrics.py
- ai2thor/util/trials.py
- tasks.py
* Adds trial runner as a generic sequence generator that gathers a metric after running controller code
* Adds a object position variance average metric used for physics determinism
* Task for testing determinism of basic actions
Results for 120 trials on a 100 random actions of each category:
```
inv get-physics-determinism -s=FloorPlan212_physics -n=120 --samples=samples
actions: 'move', object_position_variance_average: 1.0702238729969497e-11 
actions: 'rotate', object_position_variance_average: 3.6856343950937414e-12 
actions: 'look', object_position_variance_average: 4.872177661890314e-12 
actions: 'all', object_position_variance_average: 0.00029112702368825385
> Physics Determinism Test

- ai2thor/controller.py
Changes from `print` to `logging.info` for consistency with other logging across the repo.
---
For reference, every time a Controller is currently initialized it runs:
```python
print("Initialize return: {}".format(init_return))
```
Within notebooks, particularly, this is non-trivial to suppress and forever displays the print statement after initializing a Controller.
---
For one to access this info here, they'd have to set
```python
import logging
logging.basicConfig(level=logging.INFO)
```
within the script that they initialize a Controller.
> print -> logging

- unity/Assets/Scripts/ActionDispatcher.cs
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Scripts/ListExtensions.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
- unity/Assets/Scripts/UtilityFunctions.cs
1. Made some general improvements to `PlaceObjectAtPoint` and `TeleportObject`, namely improving their robustness and using the new action dispatch API.
2. I made non-trivial updates to the `InitialRandomSpawn` code to improve it's speed and the diversity of places into which objects are placed (certain random seeds were being reused resulting in less randomness as, for example, receptacles would be considered in the same order).
> Improvements to `PlaceObjectAtPoint`, `TeleportObject`, and `InitialRandomSpawn`.

- ai2thor/controller.py
- ai2thor/tests/test_unity.py
Currently, the only documented way to make updates to initialization is to call:
```python
controller = Controller(init_params)
controller.stop()
controller = Controller(new_initialization_params)
```
However, this is highly undesirable when working with an interactive shell since: 
* It takes a non-trivial amount of time to create and destroy a controller. 
* If one doesn't first call `controller.stop()` and later initializes a controller with the same name `controller`, there is no way to ever stop it (without resetting the interactive session). For instance:
```python
controller = Controller(renderDepthImage=True)
controller = Controller()
```
This PR simply extends the abilities of `reset` to not only take in a `scene` but also take in any initialization parameter, such as:
```python …
```
> Enhance reset

- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Currently, when passing in `pushAngle=0`, an error message is thrown. However, the documentation states that the push angle is accepted between 0 corresponds to a push directly in-front of the agent.
This commit:
* Allows `pushAngle=0` to work.
* Updates `DirectionalPush` from the old ServerAction input.
* Allows any float to be passed in as a `pushAngle`, where the float is then modded by 360, with the absolute value being taken.
> Fix pushAngle in DirectionalPush

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/ColorChanger.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Now, instead of destroying a controller to reset from crazy colors, that is:
```python
from ai2thor.controller import Controller
controller = Controller(scene='FloorPlan28')
controller.step('RandomColors')
controller.stop()
controller = Controller(scene='FloorPlan28')
```
one simply can call `ResetColors`:
```python
from ai2thor.controller import Controller
controller = Controller(scene='FloorPlan28')
controller.step('RandomColors')  # crazy random colors
controller.step('ResetColors')  # reset colors
```
I've also created an alias from the undocumented `ChangeColorOfMaterials` to a new name: `RandomColors`. The name `ChangeColorOfMaterials` was too hard to remember and the plurals on colors vs. materials seemed arbitrary.
This should be enough to officially support both `RandomColors` …
> enable ResetColors, alias with RandomColors

- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
**HTML colors for skyboxes.** People can now pass in the skybox color as an HTML color. For instance, one can pass in:
```python
controller.step('AddThirdPartyCamera', skyboxColor='rgb(0, 0, 255)')
controller.step('UpdateThirdPartyCamera', skyboxColor='hsl(180, 50, 50)')
controller.step('UpdateThirdPartyCamera', skyboxColor='white')
controller.step('UpdateThirdPartyCamera', skyboxColor='green')
```
This is particularly nice for top-down videos and images.
---
**Metadata Bug fixes**. Currently when calling either `AddThirdPartyCamera` or `UpdateThirdPartyCamera`, the metadata does not update its:
* `lastAction`
* `lastActionSuccess`
* `errorMessage`
* `errorCode`
since the actions are in the `AgentManager`. These changes add metadata for these 2 actions.
---
**Orthographic extensions.** …
> ThirdPartyCameras bug fixes and enhancements

- unity/Assets/Scripts/BaseFPSAgentController.cs
This provides better deprecation warnings if a user tries to call an outdated action (from unity), like `ChangeColorOfMaterials`.
> Add obsolete attribute to ChangeColorOfMaterials

- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/ActionDispatcher.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
This PR allows short circuiting action failures, which may terminate the action immediately (from any function call).
We also encourage error messages to be set within the invoked exception, so
```c#
if (failure) {
actionFinished(success: false);
errorMessage = "Failure because of XXX.";
return;
}
```
becomes:
```c#
if (failure) {
throw new <...Exception>("Failure because of XXX.");
}
```
In the former case, too, notice that errorMessage would never execute if `actionFinished` was refactored to throw an exception.
A ton of actions are functionalized. For instance, 
* `OpenObject(x, y, forceAction)` calls `getTargetObject(x, y, forceAction)` which calls `ScreenToWorldTarget(x, y, ...)`.
Previously, if `ScreenToWorldTarget` had an error, all it would do was set the `errorMessage`, but it …
> Using Exceptions to short circuit action failures

- ai2thor/server.py
Currently, printing or viewing the result of an `ai2thor.server.Event` is not particularly helpful, since it only shows:
```python
<ai2thor.server.Event at {hex ID in memory}>
```
This is particularly annoying in notebooks, since one then must always immediately call:
```python
event.metadata['lastActionSuccess']
event.metadata['errorMessage']
event.metadata['actionReturn']
```
to see if anything happened.
This PR now adds this summary information to the Event, so when users print or evaluate the Event, they will see something like:
```python
<ai2thor.server.Event at 0x7f213063ed30
.metadata['lastActionSuccess'] = True
.metadata['errorMessage'] = ""
.metadata['actionReturn'] = None
>
```
As an added benefit, it also shows new users that there is a `.metadata['lastActionSuccess']`, …
> Better Event summarization in Event.__repr__ and Event.__str__

- ai2thor/server.py
- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Aliases `PositionsFromWhichItemIsInteractable` to its new name `GetInteractablePositions`, since the former is **super** long. `GetInteractablePositions` is also more consistent with `GetReachablePositions`.
Also updates rotations to use `rotateStepDegrees`, instead of assuming that the agent is rotating in 90-degree increments.
> GetInteractablePoses, dynamic rotateStepDegrees, rotation instead of eulerAngles bug fixes

- ai2thor/controller.py
- ai2thor/fifo_server.py
- ai2thor/server.py
- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/ActionDispatcher.cs
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
Reuses the equivalent `ProcessControlCommand` from `BaseFPSAgentController`, but parameterizes the `target` object reference. 
Using the same idea, we can now call `actionFinished` and throw exceptions (#578) from `AddThirdPartyCamera` and `UpdateThirdPartyCamera` instead of the whole `actionError` and `actionSuccess` shenanigans that has been removed.
This also then fixes (and tests) many hanging bugs, such as:
```python
controller.step('AddThirdPartyCamera', ..., orthographicSize=dict(x=5, y=5))
```
where we expect `orthographicSize` to be a float.
Finally, we provide a better error message in the case that the types mismatch than what is currently provided by Json.Net.
> Bug fixes to and enhancements to ProcessControlCommand inside of AgentManager

- ai2thor/util/metrics.py
Setting path length ratio to 1.0 in `compute_single_spl` when path distance is 0 (causing `ZeroDivisionError`).
> Resolving divide by zero in compute_single_spl when path distance is 0

- scripts/update_private.py
- unity/Assets/Scripts/BaseFPSAgentController.cs
For some reason the `CheckIfAgentCanMove` and `CheckIfItemBlocksAgentMovement` don't you to give them arbitrary offsets as input, I've removed this restriction.
> Removing strange restrictions on arguments to methods checking if movement is possible.

- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
- unity/Assets/Scripts/SimObjPhysics.cs
-adding improved error messages returned on failed SetObjectPoses
-adding `placeStationary` flag to SetObjectPoses, allowing objects to be posed with kinematic = true, preventing additional physics resolution after repositioning
> Updates to SetObjectPoses

- ai2thor/controller.py
- ai2thor/interact.py
- ai2thor/server.py
- ai2thor/tests/test_unity.py
- ai2thor/util/lock.py
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Basically exposes the functionality for `getTargetObject(x, y)`, as requested in #483.
Also, I plan to deprecate every single action that uses `x`, `y`, and `objectId`, in favor of people first calling:
```python
query = controller.step("GetObjectInFrame", x=x, y=y, forceAction=True)
if query:
objectId = query.metadata['actionReturn']
controller.step('OpenObject', objectId=objectId)
```
Note that I have overwritten `__bool__` so that it points to `event.metadata['lastActionSuccess']`.
> Add GetObjectInFrame(x: float, y: float, forceAction: bool)

- README.md
- ai2thor/controller.py
- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/ActionDispatcher.cs
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/DiscreteHidenSeekAgentController.cs
- unity/Assets/Scripts/DroneFPSAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/StochasticRemoteFPSAgentController.cs
The new changes were incompatible with the locobot and drone's ability to teleport, since they do not have the ability to stand.
I've also reproduced the bug in the action dispatcher, where adding in `rotation: float` alongside `rotation: Vector3` tries to get the float to convert to a Vector3. This has not been fixed in this PR. I have simply commented out the new Teleport actions that would have allowed `rotation: float`.
> Teleport bugs

- unity/Assets/Scripts/BaseFPSAgentController.cs
The `Physics.autoSimulation` value is changed within `InitialRandomSpawn` but was not correctly reset.
> InitialRandomSpawn bugfix.

- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
originally toggleble and openable objects both attempted to access the CanToggleOnOff component, causing a null reference exception when trying to set states of openable objects that were also not toggleable
> fix to check in SetObjectStates logic

- README.md
- unity/Assets/Scripts/DebugFPSAgentController.cs
- unity/ProjectSettings/EditorBuildSettings.asset
- unity/ProjectSettings/ProjectSettings.asset
Updates to enhance the demo.
Allows for:
* All scenes to be rendered in the demo
* Removes the default loading page (I override it with a custom loading page)
* Modifies/removes some keyboard commands so that they are controllable solely through javascript. Examples include ``` and `Escape`, which used to be how one started the demo. However, there are problems with the `Escape` keyword, since it's used by the browser to allow a user to show it's cursor (after we've hidden it, and we cannot override this browser command).
> #webgl-deploy

- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
The current collision check for the arc of held objects during an agent rotation or look-up/look-down action is to take the eight corner points of the object's bounding box, and Raycast each one along their respective arc-trajectories. This is ineffective, however, if the arc overlaps with a thin or narrow object that does not intersect with any of the corner points. I updated the logic to use BoxCasts instead, so that instead of casting points, the entire bounding box of the object is cast along the arc.
Additionally, the current logic was essentially duplicated four times to accommodate the slight differences in the operations involved in turning left and right, and looking up and down. I consolidated the logic to work with all four operations by adding relevant variables and assigning …
> Added Box-Casting to CheckIfAgentCanRotate method, and consolidated logic to work for both pitching and yawing

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
Many scenes with ToggleMapView in iTHOR have pretty bad boundaries:
This now just uses the ceiling to set boundaries, if there is a ceiling structural object in the scene (i.e., iTHOR scenes). Otherwise, it sticks with the old scene boundaries (i.e., with RoboTHOR scenes).
> better mapView placement in iTHOR

- ai2thor/server.py
- ai2thor/tests/test_event.py
- ai2thor/tests/test_unity.py
This is in response to the warning generated by [lgtm.com](https://lgtm.com/projects/g/allenai/ai2thor/snapshot/abe62e40bb828e078032e19f12c4c3564e149b22/files/ai2thor/server.py?sort=name&dir=ASC&mode=list#x7715b99afd99f040:1). This removes the `__init__()` and `raw_metadata` member.  If we ever happen to need to expose access to the unfiltered dict we can create a separate method that simply delegates to `super().__getitem__(<key>)`.
> Refactor metadata wrapper

- ai2thor/controller.py
- ai2thor/tests/constants.py
- ai2thor/tests/test_unity.py
- tasks.py
- unity/Assets/Editor/Build.cs
Typically when I want to run the tests or just experiment with a few scenes in a Unity Player I will modify Build.cs to include just the scenes I care about.  This PR modifies the `local-build` task to accept a scene(s) argument and introduces a new task `local-build-test` that just builds the player with the TEST_SCENE (currently FloorPlan28). The following is now possible
```python
invoke local-build -s FloorPlan28
invoke local-build -s FloorPlan28_physics -s FloorPlan1
```
> local-build-test task / local-build with scenes

- unity/Assets/Scripts/ActionDispatcher.cs
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/ImageSynthesis/ImageSynthesis.cs
- unity/Assets/Scripts/SimObjPhysics.cs
- unity/Assets/UnitTests/TestBase.cs
- unity/Assets/UnitTests/TestDispatcher.cs
- unity/Assets/UnitTests/TestPutObject.cs
- unity/Assets/UnitTests/TestRotate.cs
Refactor invalid ActionDispatcher params logic to allow renderInstanceSegmentation to be both an action param and per step param.
> Refactoring Invalid ActionDispacher

- tasks.py
- unity/Assets/Editor/Build.cs
Adding option to local-build to include BuildScriptsOnly when running a build.  The following is now possible:
```bash
invoke local-build --scripts-only
```
I found that in order for the build run execute with any speedup `BuildOptions.Development` also needed to be included with the options.
> local-build with BuildOptions.BuildScriptsOnly 

- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/ColorChanger.cs
Solves a visual bug that only happens in a few scenes and was discovered after adding the initial `RandomizeMaterials` to the demo. Since some light rays are transparent, and others, apparently, are not, randomizing a transparent light ray to a solid light ray looks... bad.
This PR simply removes lighting materials from materials that may be randomized.
> Remove lights from randomizable materials

- unity/Assets/Scripts/ImageSynthesis/ImageSynthesis.cs
These log statements generate an enormous amount of noise in the logs - on the allenact-bench server, the unity.log file had grown to 25GB in just a few runs.
> removing log statements for imageSynthesis encode time

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
Matches the same `reset` functionality present in `RandomizeMaterials`.
While this breaks backwards compatibility, I'd consider it more of a bug fix, since calling `RandomizeColors` -> `reset()` -> `ResetColors` currently cannot reset the colors to their original ones. Moreover, this action is seldom used at this point and, I don't think, has even been used in a project yet.
> Clears RandomizeColors on reset()

- ai2thor/tests/data/arm-metadata-schema.json
- ai2thor/tests/data/metadata-schema.json
- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DroneFPSAgentController.cs
- unity/Assets/Scripts/Fill.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/SimObjPhysics.cs
For [Fill Object with Liquid](https://ai2thor.allenai.org/ithor/documentation/object-state-changes/#fill-object-with-liquid):
* Adds `fillLiquid` to metadata .
* Bug fixes the action to make sure each failed path terminates immediately (i.e., with `throw new Exception()`)
> Add fillLiquid to metadata

- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Minimal bug fix to `directionalPush` to support 0 degrees as an angle. It also adds support for negative angles and angles >= 360 to match the `degrees` functionality present in rotate actions.
> minimal directionalPush bug fix

- unity/Assets/Scripts/SimObjPhysics.cs
Prior to moving gameObjects to the NonInteractive layer, save their state.  This fixes an issue where a component that has two colliders gets restored incorrectly to the NonInteractive layer since the second iteration through the loop causes the gameObject to get restored to the NonInteractive layer.
> Save state of gameObject's layer for all colliders during oobb generation

- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/AgentManager.cs
In regards to 3rd party cameras, this fixes an issue where light and shadow resolutions were dynamically scaled based on the clipping plane values, so defaulting this to the same clipping planes as the agent camera for parity
> adding default values to near/far clipping planes

- scripts/ai2thor-xorg
This PR adds the following option to the ai2thor-xorg command:
```python
sudo ai2thor-xorg --exclude-device 0 start
```
This will ignore the first GPU identified by device id `0`.
> ai2thor-xorg - adding option to exclude a device

- unity/Assets/Scripts/ImageSynthesis/ImageSynthesis.cs
For an explanation, read this interactive notebook which visually shows what is going on and what happens if one naively removes the disabling out of the light rays (i.e., they may appear in the segmentation frames):
https://colab.research.google.com/drive/16kzdy7DNc5dCPHBt5z0Qgm3FWvy6-4wk?usp=sharing
The only way this may fail is if a light ray object (which only occurs in a few rooms, and also caused #754 ) does not actually have the name "LightRay". However, in the few scenes I've found that do have light rays, all of them are named `LightRay`, and there doesn't appear to be a better way to find them.
> Support `RandomizeMaterials` and `RandomizeColors` with Image Synthesis on.

- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/ProceduralTools.cs
-adding floor mesh colliders to all generated sub floors, set to lits own layer
-adds floorCheck raycast against floor layer to ensure spawned objects only appear over parts of floor object with a mesh renderer
> adding floor mesh colliders

- unity/Assets/Physics/SimObjsPhysics/Bathroom Objects/ToiletPaper/Prefabs/ToiletPaper.prefab
Fixed outstanding trigger collider on sole ToiletPaper prefab, which was inflating the realtime-generated bounding box to absurd dimensions
> Fixed rogue trigger collider on ToiletPaper prefab

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
instead of re-assigning objectId every time an object is removed from the scene, only the key for that object is removed from the objectIdToSimObjPhysics dict.
This prevents issues with objectId being re-assigned incorrectly due to floating point errors.
Additionally, moved DisableAllObjectsOfType to base controller to be in line with the EnableObject() and DisableObject() actions. Added notes to these actions for when a more comprehensive update of the objectId assignment logic is revamped.
> Fix to RemoveFromScene objectId assignment

- unity/Assets/Scripts/ArmAgentController.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
Now if you hold shift while in the debug editor window you can move the arm with the arrow keys and s/w. I also added an arm action for allowing relative movements (it's quite cumbersome to always have to specify absolute coordinates).
One "fix" I added that I'd like comments on: I noticed that when moving the arm, the position of the arm can become desynched with the position of the `IK_pos_rot_manipulator`. This is quite counter intuitive to me (as there is some invisible state that changes how functions behave) so I now ensure that the position of the `IK_pos_rot_manipulator` is always reset to the position of the arm after taking a `MoveArm` or a `MoveArmRelative` action.
> Better arm editor debugging and allowing relative arm movement.

- ai2thor/platform.py
This was generating an error:
```TypeError: 'Display' object is not subscriptable```
It was wrongly used. The line 123 (for example) shows the correct usage.
> fix: disp_screen is an object

- ai2thor/tests/test_unity.py
- unity/Assets/Scenes/FloorPlan_ExpRoom.unity
- unity/Assets/Scripts/ArmAgentController.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/DroneFPSAgentController.cs
- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/StochasticRemoteFPSAgentController.cs
This should only be merged after #801.
This PR:
* Fixes a bug where an objects held by the arm would not interact with other (non-kinematic) objects.
* Adds Move(Ahead/Back/Left/Right) and Rotate(Left/Right) actions to the arm controller.
* Removes the Move(Ahead/Back/Left/Right) and Rotate(Left/Right) actions form the base controller (these are always overwritten and so should not exist).
* Move the Move(Ahead/Back/Left/Right) and Rotate(Left/Right) to the action dispatch API.
> Fixing arm collision bug and cleaning up move/rotation actions.

- unity/Assets/Scripts/ArmAgentController.cs
- unity/Assets/Scripts/ContinuousMovement.cs
- unity/Assets/Scripts/DebugDiscreteAgentController.cs
- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
This should only be merged after #803. Note that I've targeted this merge at the `arm-collision-test` branch so that it's easier to see the differences, it should actually be merged to main after approval.
This PR:
* Replaces the `RotateMidLevelHand` method with a `RotateWristRelative` action. As it sounds, this allows for rotating the arm's wrist given an input pitch, yaw, and roll. I've hooked up this action into the debug editor, try it out by using `shift+alt+(arrow keys and w/s)` (I think it's fairly intuitive).
* Adds `RotateElbow` and `RotateElbowRelative` commands to allow for rotating the arm's elbow. Try this with `shift+alt+(q/e)`
* Enables a special "teleportation" case in arm movement/rotation: when taking an arm action with `speed` set to `float.PositiveInfinity` and …
> Allowing for rotating the wrist & elbow in a relative fashion.

- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Renames `DropHandObject` to `DropHeldObject`. In iTHOR, its unclear what the "hand" is.
Everything is backwards and sideways compatible. That is; users can still pass in `DropHandObject` to older and newer versions, and it will still work.
> DropHandObject -> DropHeldObject

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
Now allows third party cameras to be used in place of ToggleMapView with
```python
from ai2thor.controller import Controller
event = controller.step(action="GetMapViewCameraProperties")
controller.step(
action="AddThirdPartyCamera",
**event.metadata["actionReturn"]
)
```
I don't think these should be merged into a single action, because, eventually, Third Party Cameras should be deprecated in favor of having the camera actually be an agent.
Resolves https://github.com/allenai/ai2thor/issues/812.
Fixes https://github.com/allenai/ai2thor/issues/445.
Deprecates `ToggleMapView`.
> Top-Down Image Frame Updates

- unity/Assets/Editor/PhysicsSettler.cs
- unity/Assets/Resources/ThirdPartyCameraTemplate.prefab
- unity/Assets/Resources/ThirdPartyCameraTemplate.prefab.meta
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/ArmAgentController.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/ContinuousMovement.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
* The `handSphereCenter` returned by the metadata was not in world space coordinates.
* Some actions used by the arm do not advance physics (e.g. `PlaceObjectAtLocation`). This means that **objects may be moved by an action without their transforms being synchronized**; I noticed this problem when the bounding box returned for an object failed to update after using `PlaceObjectAtLocation`. To fix this, I now wrap the `Physics.Simulate` function so that we record whether or not physics has been simulated and, if not, I synchronize the transforms before computing metadata.
* The arm would fail to move if moved less than ~0.03 meters. This was fixed by changing `epsilon` from `1e-3` to  `1e-6`, the arm will now only fail to move if moved less than 1cm.
Added an anti-aliasing option for 3rd …
> Fixing arm bugs, adding new action allowing for rotating an object held by the arm, and adding anti-aliasing option to 3rd party cameras.

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/UnitTests/TestBase.cs
- unity/Assets/UnitTests/TestThirdPartyCamera.cs
~~- adds new action `CoordinateFromRaycastThirdPartyCamera` that allows getting coordinates of objects hit from a ThirdPartyCamera raycast (same as GetCoordinateFromRaycast for the main agent camera)~~
- updates some DebugInput field syntax to not use outdated `ActionDispatcher` syntax, instead use new `ProcessControlCommand` overload
- removes extra `AddComponent` call in `AddThirdPartyCamera` since camera prefabs now already have a camera component on them
~~- unit tests for ThirdPartyCamera instantiation as well as new CoordinateFromRaycastThirdPartyCamera~~
Edit: All functions related to `CoordinateFromRaycastThirdPartyCamera` are now isolated to the [`CoordinateFramRaycastTPC`](https://github.com/allenai/ai2thor/tree/CoordinateFromRaycastTPC) branch to make future updates to …
> ThirdPartyCamera New Action and Bug Fixes

- unity/Assets/Scripts/ProceduralTools.cs
Since we're separating the floors into individual SimObjects now, this tool I wrote takes each floor-mesh, splits up the polygons into right triangles, and generates vispoints for each one along a grid originating from each triangle's right angle, with an increment defined by the user. This will allow each triangle to be optimally covered with vispoints, no matter how granular the triangulation.
> Added automated floor vispoint generation

- scripts/ai2thor-xorg
Allowing for changing the height/width of the x display when running `ai2thor-xorg start` by using the `--height` and `--width` flags.
> Parameterizing height/width in `ai2thor-xorg start`

- unity/Assets/Physics/SimObjsPhysics/Common Objects/DiningTable/Prefabs/Dining_Table_Master_Prefabs/Dining_Table_23_Master.prefab
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/Break.cs
- unity/Assets/Scripts/InstantiatePrefabTest.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/PhysicsSceneManager.cs
- unity/Assets/Scripts/SimObjPhysics.cs
- unity/Assets/UnitTests/TestPutObject.cs
- adds a line to ensure the child game object used for `BoundingBox` for all sim objects correctly has its local position zeroed out. 
- forces any objects that are about to break to drop an child objects contained by them. This fixes issues of some objects disappearing on `InitialRandomSpawn` when certain receptacles break. Previously, if something like an Apple was placed inside a breakable plate via `InitialRandomSpawn` with `placeStationary = True` it would not be "dropped" by the receptacle and was deactivated a the plate breaks.
- adds new `MakeAllObjectsUnbreakable` and `MakeAllObjectsBreakable` actions to be used with `InitialRandomSpawn`
- adds a check to not reposition receptacles that have had another object spawn inside of them during the `InitialRandomSpawn` process. The …
> Object Bounds Fix

- ai2thor/tests/data/arm-metadata-schema.json
- ai2thor/tests/data/metadata-schema.json
- doc/static/ReleaseNotes/ReleaseNotes_2.0.md
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/ColdZone.cs
- unity/Assets/Scripts/DroneFPSAgentController.cs
- unity/Assets/Scripts/Fill.cs
- unity/Assets/Scripts/HeatZone.cs
- unity/Assets/Scripts/SimObjPhysics.cs
This is a backwards breaking change (in line with https://github.com/allenai/ai2thor/pull/824) in the object metadata that renames the `ObjectTemperature` key to `temperature`.
The capitalization of the `ObjectTemperature` metadata key is inconsistent with all the other metadata keys (i.e., should be `camelCase`).
- ObjectTemperature was referenced a few times in the documentation (see: https://github.com/allenai/ai2thor.allenai.org/search?q=ObjectTemperature). However, these were mostly in the description of temperature decay descriptions.
- However, on the [2.0 release note](https://github.com/allenai/ai2thor/blob/main/doc/static/ReleaseNotes/ReleaseNotes_2.0.md#state-changes-added-to-object-metadata), it was actually incorrectly documented, saying that the key was `objectTemperature` …
> Rename `ObjectTemperature` to `temperature`

- ai2thor/platform.py
Was getting the error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-18ecdd6422e8> in <module>()
----> 1 controller = Controller(makeAgentsVisible=False, width=1000, height=1000)
4 frames
/usr/local/lib/python3.7/dist-packages/ai2thor/platform.py in _validate_screen(cls, display_screen_str, width, height)
116                         width,
117                         height,
--> 118                         disp_screen["width_in_pixels"],
119                         disp_screen["height_in_pixels"],
120                     )
TypeError: 'Display' object is not subscriptable
```
Based on https://github.com/allenai/ai2thor/blob/main/ai2thor/platform.py#L109, it looks …
> disp_screen indexing bug fix

- scripts/ai2thor-xorg
Setting Interactive to "False" to prevent processes from getting killed.
https://download.nvidia.com/XFree86/Linux-x86_64/340.108/README/xconfigoptions.html
> ai2thor-xorg - adding Interactive false to Screen section

- unity/Packages/manifest.json
- unity/Packages/packages-lock.json
Removing TextMeshPro package. Package is unused.
For completeness, the motivation behind the PR is to try and get all the package requirements between the CloudRendering build (Unity 2021.2 Alpha) and our current build to be the same so we don't have to maintain a separate branch for the CloudRendering code.
> Remove TextmeshPro

- unity/Assets/Scripts/BaseFPSAgentController.cs
Instead of returning a list of:
```python
[
{
"id": "Blinds",
"type": "Blinds",
"primaryProperty": "Static",
"secondaryProperties": [],
"boundingBox": {
"min": {
"x": -0.42500001192092896,
"y": 2.0952999591827393,
"z": -1.4369999170303345
},
"max": {
"x": 0.6539999842643738,
"y": 2.3373000621795654,
"z": -1.4369999170303345
}
}
},
{
"id": "Mirror",
"type": "Mirror",
"primaryProperty": "Static",
"secondaryProperties": [],
"boundingBox": {
"min": {
"x": -0.8920000791549683,
"y": 1.069000005722046,
"z": 0.5980000495910645
},
"max": {
"x": -0.8450000286102295,
"y": 1.7070000171661377,
"z": 1.125
}
}
},
...,
]
```
it returns a dict with ids as keys:
```python
{
"Blinds": {
"objectType": "Blinds",
"primaryProperty": "Static",
"secondaryProperties": [],
"boundingBox": {
"min": {
"x": …
```
> Change Asset Metadata Type

- unity/Assets/Physics/SimObjsPhysics/Communication Objects.meta
- unity/Assets/Physics/SimObjsPhysics/Communication Objects/Objects to Spawn.meta
- unity/Assets/Physics/SimObjsPhysics/Communication Objects/Objects to Spawn/Television_1_Stand.prefab
- unity/Assets/Physics/SimObjsPhysics/Communication Objects/Objects to Spawn/Television_1_Stand.prefab.meta
Reverts allenai/ai2thor#894.
It is breaking calls to `GetAssetDatabase`, for some reason. Gives the error message:
```
NullReferenceException: Object reference not set to an instance of an object. trace:   at UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController.GetAssetDatabase () [0x00043] in <acacb5545566412ca64753e1a75f7e5e>:0    at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 
```
Can be investigated later, I can remove this …
> Revert "Remove Communication Objects"

- ai2thor/controller.py
- ai2thor/platform.py
- ai2thor/tests/test_controller.py
This PR adds a new parameter `platform` to the `ai2thor.controller.Controller` constructor.  Prior to this, in order to run say a CloudRendering and Linux64 (Xorg dependent Unity), you would have to do something like this:
```python
import ai2thor.controller
import ai2thor.platform
ai2thor.platform.CloudRendering.enabled = True
ai2thor.platform.Linux64.enabled = False
cloudrendering_controller = ai2thor.controller.Controller()
ai2thor.platform.CloudRendering.enabled = False
ai2thor.platform.Linux64.enabled = True
xorg_controller = ai2thor.controller.Controller()
```
With this change, the following can now be done:
```python
import ai2thor.controller
from ai2thor.platform import CloudRendering, Linux64
xorg_controller = ai2thor.controller.Controller(platform=Linux64) …
```
> Add platform as Controller() constructor param

- ai2thor/tests/test_unity.py
- setup.py
- unity/Assets/Scripts/CanOpen_Object.cs
- unity/Assets/Scripts/CanToggleOnOff.cs
- unity/Assets/Scripts/SimObjPhysics.cs
I discovered that the way that we generate OOBB will wake some rigid bodies up causing them to never settle.  This can be observed by calling `Physics.Simulate()` repeatedly and examining the position and rotation values for the `Lettuce` object in FloorPlan28.  The issue is that when any change is done to the transform of a GameObject Unity will wake the RigidBody.  What this PR does is clone the GameObject and place it at the origin and then perform the OOBB calculation.
One thing that I also noticed was that during the `Object.Instantiate` call , `iTween.Init` needed be be called on the newly cloned objects otherwise iTween would throw an error about a null GameObject. This is the reason for moving the `iTween.Init` calls to `Awake` from `Start` for `CanOpen` and `CanToggle`.
> Clone GameObject when generating OOBB

- ai2thor/controller.py
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
The CloudRendering platform does not respect command-line parameters, so the Quality is updated manually after startup/reset.
* moving ChangeQuality to AgentManager
* Calling ChangeQuality for CloudRendering after startup
> Calling changequality for CloudRendering after startup; 

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/StretchAgentController.cs
Simple way of updating secondary camera image synthesis based on main camera
> Stretch robot restructured arm updated secondary camera image synthesis

- ai2thor/build.py
- ai2thor/controller.py
Calls to `ChangeResolution` fail when connecting from Python to the Unity Editor.  This PR resolves that.
> Fix Python+WSGI -> Unity Editor

- ai2thor/controller.py
There is currently a pretty ugly error message on `main` when an unknown scene in passed in:
The error message occurs because we try to sort by the pattern `re.search(r"FloorPlan[_]?([a-zA-Z\-]*)([0-9]+)_?([0-9]+)?.*$", scene_name)`. But, not all scenes in the `main` build work with the pattern anymore. For instance, trying it with `FloorPlan_ExpRoom` results in `None`, which then results in the AttributeError: `'NoneType' object has no attribute 'group'`.
This PR just calls `sorted()` instead of trying to sort by `key_sort_func`. The downside is that it may be a little less natural, where `FloorPlan10` might come before `FloorPlan1`, but it's much more robust to new scene names in the build.
Full notebook: https://colab.research.google.com/drive/1207Px1enUPqzJ2mTIkvrc-OA7eygpEyT?usp=shari …
> Better error message when passing in unknown scene

- unity/Assets/Physics/Scene Setup Prefabs/PhysicsSceneManager.prefab
- unity/Assets/Physics/SimObjsPhysics/Custom Project Objects/FurnMove/MATVStand.prefab
- unity/Assets/Physics/SimObjsPhysics/Custom Project Objects/FurnMove/MATVStand.prefab.meta
At some point a prefab was removed from the `InstantiatePrefabTest` script attached to the `PhysicsSceneManager`. This has caused the spawning scripts to break (e.g. `CreateObject`, try `spawn Tomato` in the debug editor). I have added back the old dresser prefab that was deleted and updated the `PhysicsSceneManager`.
> Fixing broken InstantiatePrefabTest.

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
This PR removes the ScreenSpaceAmbientOcclusion component from the FirstPersonCharacter/FPSController prefab.  We no longer use SSAO and it can get re-enabled if `ChangeQuality` is called with a value other than Low or Very Low.  This results in the following frame:
Note the difference when compared to the frame received with quality set to Ultra, but never calling `ChangeQuality`
> Remove SSAO component from FirstPersonCharacter

- ai2thor/fifo_server.py
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
Without this parameter `msgpack` would fail when given data corresponding to a dictionary with integer valued keys.
Also made a small change to integer rounding for one function.
> Adding `strict_map_key=False` as an argument for `msgpack.loads`.

- scripts/ai2thor-xorg
When a monitor is connected to a graphics device it must be excluded from a headless Xorg configuration otherwise X will fail to start.  This option is documented here: https://download.nvidia.com/XFree86/Linux-x86/1.0-8756/README/appendix-d.html
Tesla/GRID GPUs don't support this option and Xorg will fail to start if the option is present.  This is the reason that the option can't simply be included for all configurations.
> ai2thor-xorg UseDisplayDevice None

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
Adds  option of `position` argument to `ObjectNavExpertAction` to track a position instead of a SimObject when `objectType` and `objectId` are not passed.
> Expert action accepting target position

- unity/Assets/Physics/SimObjsPhysics/Common Objects/SideTable/Prefabs/Side_Table_Master_Prefabs/Side_Table_313_Master.prefab
- unity/Assets/Scenes/FloorPlan10_physics.unity
- unity/Assets/Scenes/FloorPlan12_physics.unity
- unity/Assets/Scenes/FloorPlan15_physics.unity
- unity/Assets/Scenes/FloorPlan18_physics.unity
- unity/Assets/Scenes/FloorPlan21_physics.unity
- unity/Assets/Scenes/FloorPlan25_physics.unity
- unity/Assets/Scenes/FloorPlan26_physics.unity
- unity/Assets/Scenes/FloorPlan2_physics.unity
- unity/Assets/Scenes/FloorPlan409_physics.unity
- unity/Assets/Scenes/FloorPlan7_physics.unity
Fixes toward issue #975 
Some nested sim objects were set up such that their parent sim object referenced the nested object's visibility points in the parent sim object's array. This caused the arrays to have null references when the child sim object was removed from the scene via actions like `RemoveFromScene`.
This PR fixes all objects erroneously referenced in this way.
> Fixes visibility point array references to child sim objects in some scenes

- ai2thor/controller.py
- ai2thor/tests/test_controller.py
This PR ensures that the `gpu_device` Controller param matches the indexes returned from nvidia-smi.
> mapping gpu_device to Vulkan device index

- unity/Assets/Scripts/BaseFPSAgentController.cs
Changing GetComponent to GetComponentInChildren when getting UnityEngine.AI.NavMeshAgent.
> Minor fix to grab NavMeshAgent correctly.

- unity/Assets/Scripts/IK_Robot_Arm_Controller.cs
- unity/Assets/Scripts/Stretch_Robot_Arm_Controller.cs
We've found rare cases where the `Controller` hangs forever if `Destroy` is called. Hanging occurs very inconsistently and after several millions of steps during training, making it extremely hard to debug.
This attempts to work around the use of the Destroy function here by reusing the same surrogateChild object if it has been created, otherwise, it creates a new one.
> Remove `Destroy` inside of GenerateMetadata

- unity/Assets/Scripts/BaseFPSAgentController.cs
* Throws error when setting `snapToGrid` to `true` and `rotateStepDegrees` to something different than 0, 90, 180, 270 or modulo 0 of 360, which mean can make it go outside of the grid.
> snapToGrid error when stepDegrees not 90, 180, 270

- unity/Assets/Scripts/LocobotFPSAgentController.cs
This reverts a change made several months ago and allows the locobot to look upwards above the horizon line.
This PR also allows the locobot to look downwards by up to 60 degrees as is mentioned in the documentation.
> Changing the maxUpwardLookAngle of the locobot so that it can look upwards by up to 30 degrees.

- ai2thor/controller.py
- ai2thor/fifo_server.py
- ai2thor/server.py
- ai2thor/tests/test_unity.py
- ai2thor/wsgi_server.py
- unity/Assets/Scripts/BaseFPSAgentController.cs
We have code that times out the AI2-THOR unity process if it doesn't respond to a request in some number of seconds when using the WSGI server. Similar code did not seem to exist for the, now default, fifo server. This PR adds this timeout functionality (with tests) and adds a few small typing improvements.
> Improvements to how timeouts are handled.

- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
Pretty simple change. The stretch arm's pos-rot now starts at a default position of 0.1m up, and 180 y-degrees left, so that it won't collide with anything that the agent's body wouldn't as well, removing it as a liability for tight spaces
.
> Adjusted stretch arm default pose to be more compact

- ai2thor/controller.py
- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/AgentManager.cs
Moves #1039 to the nanna branch. Hopefully also fixes the failing tests.
> Removing agentControllerType initialization parameter on nanna branch.

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Standard Assets/Characters/FirstPersonCharacter/Prefabs/FPSController.prefab
Fixing Stretch-Robot's default PosRotManipulator Transform to be at better default position, and not catch on objects during locomotion
> Stretch robot default posrot fix

- tasks.py
The current build script doesn't output very much information about what did, or did not, fail and in how much time. This PR adds some additional logging and should fail faster when appropriate.
> Adding additional logging to the CI build script and using more explicit communication between processes.

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
Updating an edge case where a target object is not visible to the agent in any place on the navigation path due to agent parameters. Sometimes, different combinations of `gridSize` and `fieldOfView` and `visibilityDistance` may lead to objects being unable to be found when trying to path to them via the shortest path action.
This update adds a more detailed exception to be thrown when this happens, as the previous exception was caught too late and pointed to an unrelated error that wasn't actually happening.
> Update to shortest path error message

- ai2thor/controller.py
- ai2thor/fifo_server.py
- ai2thor/hooks/procedural_asset_hook.py
- ai2thor/util/runtime_assets.py
- setup.py
- tasks.py
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseAgentComponent.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/DroneFPSAgentController.cs
- unity/Assets/Scripts/LocobotFPSAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/ProceduralTools.cs
- unity/Assets/Scripts/StretchAgentController.cs
- unity/Assets/UnitTests/TestThirdPartyCameraAndMainCamera.cs
The newly added SpawnBoxCollider function generates a box with an active collider encapsulates the agent. Currently, it only supports the Stretch agent.
New augments:
1. `useFPINCollider`: bool. When set to True, SpawnBoxCollider is included during the initialization phase. If False, initialization proceeds as previously.
2. `colliderScaleRatio`: dict. It specifies the scale ratio of the box along each axis, for example, `{"x": 1.0, "y": 1.0, "z": 1.0}`. A value of 1.0 indicates that the box size matches the detected bounds.
> add SpawnBoxCollider func

- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/PhysicsExtensions.cs
- unity/Assets/Scripts/ProceduralTools.cs
- unity/Assets/Scripts/Stretch_Robot_Arm_Controller.cs
- unity/Assets/Scripts/UtilityFunctions.cs
The old `isObjectColliding` function did not check for mesh colliders as all dynamic objects previously used only primitive colliders. This changed with Objaverse and so this function needed to be updated.
This commit also includes a change to how the skybox is setup when a procedural house is loaded with a uniform color skybox. The idea here is that we don't want the skybox to effect lighting in the scene as this can result in some really weird behavior (i.e. objects rendered on a pure white background are very overexposed).
> Fixing collision checks to work correctly with convex colliders.

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/BaseFPSAgentController.cs
- unity/Assets/Scripts/StretchAgentController.cs
- unity/Assets/UnitTests/TestThirdPartyCameraAndMainCamera.cs
This updates agent main camera and third party camera returned metadata to be more descriptive and have parity with each other in terms of naming convention and what values are returned. The idea is any camera, main or third party, will always return their position and rotation coordinates in world space and relative to the agent. Third party cameras additionally return position and rotation relative to any parent they might have as third party cameras may be attached to specific segments of articulated agents at some point.
This also fixes a silent bug where third party camera values may have not been correctly being calculated relative to the agent in some circumstances.
metadata now has
- **_worldRelativeCameraPosition_** - New metadata added. same as AgentMetadata.cameraPosition which …
> Updating Agent Metadata and ThirdPartyCamera Metadata

- ai2thor/controller.py
- ai2thor/hooks/procedural_asset_hook.py
- tasks.py
- unity/Assets/Scripts/FpinAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/ProceduralTools.cs
* Changes hooks to callbacks
* Adds ProceduralAssetCallback that pople actually use, how the cache works
* Throws exceptions for deprecated arguments
* CreateHouse with invalid ids points to the new ProceduralAsset documentation
> 6.0.0 Release changes

- ai2thor/tests/data/arm-metadata-schema.json
- ai2thor/tests/test_unity.py
- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/ArmAgentController.cs
- unity/Assets/Scripts/DiscreteHidenSeekAgentController.cs
- unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs
- unity/Assets/Scripts/StretchAgentController.cs
- unity/Assets/Scripts/UtilityFunctions.cs
- unity/Assets/UnitTests/Procedural/Movement/TestProceduralTeleport.cs
- unity/Assets/UnitTests/TestThirdPartyCameraAndMainCamera.cs
The purpose of these updates is to prevent an edge case where, when using an arm-typed agent, calling the Teleport action would cause the isStanding value to default in a weird way, causing the main camera of the arm-typed agent to be changed unexpectedly back to a default position that only has context for the high-level-agent. This update also catches a case where, when using the high-level agent and calling `UpdateMainCamera`, the `isStanding() return became ambiguous.
- adding an override to the Teleport/TeleportFull actions in the `ArmAgentController` class and its derived classes so that an error can be thrown if passing in the `standing` bool since arm agents don't have a concept of a standing vs crouching camera position
- updating the isStanding() helper function to return `null` …
> Updates to Teleport/TeleportFull and isStanding()

- unity/Assets/Scripts/AgentManager.cs
- unity/Assets/Scripts/DebugInputField.cs
- unity/Assets/Scripts/UtilityFunctions.cs
This adds a quick action that allows the agent to turn off the default syncing of certain parts of some agent body mesh and the actual main camera game object (ie: the "head" of the high level agent or the mounted camera of the stretch agent) 
Because we now allow more control over main camera positions relative to the agent body via the `UpdateMainCamera()`, this action can be used in tandem to ensure a modified main camera does not adversely affect the agent's mesh representation.
> Toggle Main Camera Mesh Tracking
